-- Reference data: the instruments (ETFs / stocks) the ledger can transact in.
create table instrument (
    ticker     varchar(32)  primary key,
    name       varchar(128) not null,
    currency   varchar(3)   not null,
    type       varchar(16)  not null,
    created_at timestamptz  not null default now()
);

-- The transaction ledger. Money and quantities are NUMERIC — never floating point.
create table transaction (
    id               bigint generated by default as identity primary key,
    ticker           varchar(32)    not null references instrument (ticker),
    type             varchar(16)    not null,
    quantity         numeric(19, 6) not null,
    price_per_unit   numeric(19, 6) not null,
    currency         varchar(3)     not null,
    fee              numeric(19, 6) not null default 0,
    transaction_date date           not null,
    external_id      varchar(128),
    created_at       timestamptz    not null default now()
);

create index ix_transaction_ticker on transaction (ticker);
create index ix_transaction_date on transaction (transaction_date);

-- Dedup key for idempotent CSV import (Step 2): when external_id is present it must be
-- unique, but multiple manually-entered rows may leave it null.
create unique index uq_transaction_external_id
    on transaction (external_id)
    where external_id is not null;
