-- Market-data tables backing portfolio valuation (Step 3). Rows are seeded manually for
-- now; Step 5 adds a scheduled job that upserts into them via the unique constraints below.

-- Daily close price per instrument, in the instrument's own currency. One row per
-- (ticker, price_date); the unique constraint backs the idempotent ON CONFLICT upsert later.
create table price_history (
    id          bigint generated by default as identity primary key,
    ticker      varchar(32)    not null references instrument (ticker),
    price_date  date           not null,
    close_price numeric(19, 6) not null,
    currency    varchar(3)     not null,
    created_at  timestamptz    not null default now(),
    constraint uq_price_history_ticker_date unique (ticker, price_date)
);

-- Latest-price lookups order by date descending within a ticker.
create index ix_price_history_ticker_date on price_history (ticker, price_date desc);

-- Daily FX rates. Convention: 1 unit of base_currency = `rate` units of quote_currency
-- (e.g. base=USD, quote=SGD, rate=1.35 means 1 USD = 1.35 SGD). Extra scale on `rate`
-- because FX quotes carry more significant digits than money amounts.
create table fx_rate (
    id             bigint generated by default as identity primary key,
    rate_date      date           not null,
    base_currency  varchar(3)     not null,
    quote_currency varchar(3)     not null,
    rate           numeric(19, 8) not null,
    created_at     timestamptz    not null default now(),
    constraint uq_fx_rate_date_pair unique (rate_date, base_currency, quote_currency)
);

-- Latest-rate lookups order by date descending within a currency pair.
create index ix_fx_rate_pair_date on fx_rate (base_currency, quote_currency, rate_date desc);
